LOCAL_CONFIG ?= local_config.mk
-include $(LOCAL_CONFIG)

DEBUG ?= 0
OPT_LVL ?= 3

ENABLE_CS ?= 0
ENABLE_NVBIT ?= 0
ENABLE_ROCM ?= 0
ENABLE_TORCH ?= 0

all:
	ENABLE_COMPUTE_SANALYZER_BACKEND=$(ENABLE_CS) \
	ENABLE_NVBIT_BACKEND=$(ENABLE_NVBIT) \
	ENABLE_AMD_ROCM_BACKEND=$(ENABLE_ROCM) \
	ENABLE_TORCH_MONITOR_BACKEND=$(ENABLE_TORCH) \
	./bin/build DEBUG=$(DEBUG) OPT_LVL=$(OPT_LVL)

clean:
	./bin/clean
